### ISSUE TITLE
Request - Vehicle Slot Restriction

### ISSUE THREAD

**Issue by kMaN175** [Malbryn/MalFramework#393]
Add a module to the framework that would restrict a vehicle slot to a specific unit.

- Example: Pilot unit can only get into the helo's pilot and copilot seat.

**Comment by kMaN175** [comment]
Right now, this works in MP & dedicated.

Put in init.sqf:
allowedPlayers = ["p1","p2","p3","p4"];

Put in Variable Name of unit:
p1

Put in ini of vehicle:
this addEventHandler [ 
"GetIn", 
{ 
 _v = _this select 0; 
 _player = _this select 2; 
 _on = owner _player; 
 if (_player == (driver _v)) then { 
  if (!((vehicleVarName _player) in allowedPlayers)) then { 
   [ 
    { 
     sleep 2; 
     if (!((vehicle player) isKindOf "Man")) then { 
      moveOut player; 
     };  
     hintSilent "You are not Allowed!"; 
    }, 
    "BIS_fnc_spawn", 
    _on, 
    FALSE 
   ] spawn BIS_fnc_MP; 
  }; 
 }; 
} 
];

**Comment by johnb432** [comment]
> Right now, this works in MP & dedicated.
> 
> Put in init.sqf: allowedPlayers = ["p1","p2","p3","p4"];
> 
> Put in Variable Name of unit: p1
> 
> Put in ini of vehicle: this addEventHandler [ "GetIn", { _v = _this select 0; _player = _this select 2; _on = owner _player; if (_player == (driver _v)) then { if (!((vehicleVarName _player) in allowedPlayers)) then { [ { sleep 2; if (!((vehicle player) isKindOf "Man")) then { moveOut player; }; hintSilent "You are not Allowed!"; }, "BIS_fnc_spawn", _on, FALSE ] spawn BIS_fnc_MP; }; }; } ];

The problem I see with your solution is that it doesn't take into account if a player switches seats inside the vehicle.
The code itself it very much outdated (still certainly works, but there are much better methods to do stuff nowadays).
Also, the code just kicks the player outside of the vehicle - it might be better to put them in a passenger seat instead.

```SQF
_this addEventHandler ["GetIn", {
    params ["_vehicle", "_role", "_player"];
    
    if (isPlayer _player && {_role in ["driver", "gunner", "commander"]} && {!isNil "allowedPlayers"} && {!((vehicleVarName _player) in allowedPlayers)}) then {
        // Filters seats occupied by alive passengers out
        private _cargoIndex = ((fullCrew [_vehicle, "cargo", true]) select {!alive (_x select 0)}) apply {_x select 2};
        
        // If not space in cargo, eject player
        if (_cargoIndex isEqualTo []) then {
            moveOut _player;
            "You are not allowed to get into crew slots!" remoteExecCall ["systemChat", _player];
        } else {    
            _player action ["moveToCargo", _vehicle, _cargoIndex select (count _cargoIndex - 1)];
            "You are not allowed to get into crew slots!" remoteExecCall ["systemChat", _player];
        };
    };
}];

_this addEventHandler ["SeatSwitched", {
    params ["_vehicle", "_player"];
    
    private _role = _player call CBA_fnc_vehicleRole;
    
    if (isPlayer _player && {_role in ["driver", "gunner", "commander"]} && {!isNil "allowedPlayers"} && {!((vehicleVarName _player) in allowedPlayers)}) then {
        // Filters seats occupied by alive passengers out
        private _cargoIndex = ((fullCrew [_vehicle, "cargo", true]) select {!alive (_x select 0)}) apply {_x select 2};
        
        // If not space in cargo, eject player
        if (_cargoIndex isEqualTo []) then {
            moveOut _player;
            "You are not allowed to get into crew slots!" remoteExecCall ["systemChat", _player];
        } else {    
            _player action ["moveToCargo", _vehicle, _cargoIndex select (count _cargoIndex - 1)];
            "You are not allowed to get into crew slots!" remoteExecCall ["systemChat", _player];
        };
    };
}];
```
Handles seat switching and getting in - puts units in cargo if no space found.
If you don't want player mounting up at all, you should lock the vehicle regardless.
It would have to be added on a per vehicle basis.

**Comment by kMaN175** [comment]
I was only using it on a helo and you couldn't switch to the pilot or copilot seat from a crew or passenger seat.

The code that you provided would need to put that in each vehicle .ini?

**Comment by johnb432** [comment]
> I was only using it on a helo and you couldn't switch to the pilot or copilot seat from a crew or passenger seat.
> 
> The code that you provided would need to put that in each vehicle .ini?

I haven't tested the code you put there, but going off of the [wiki](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#GetIn) - it shouldn't. But if it does work, then ¯\_(ツ)_/¯

Yes, it would need to be put into each vehicle's init.
I figure that vehicles you don't want players getting into anyways should be locked.

However, it could be added to players too though, with some sort of condition to filter the allowed players out (in the code above it's allowedPlayers).

To get the proposed solution to work on players you'd only need to change the first EH type to [getInMan](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#GetInMan) and the second EH type to [seatSwitchedMan](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#SeatSwitchedMan).

You'd need to add it to the player's init instead of the vehicle's.

**Comment by kMaN175** [comment]
Thought about what you said and discovered that you can get in as co-pilot and switch to the pilot seat. :(
