### ISSUE TITLE
more TFAR settings - add tfar additional channel and stereo settings support

### ISSUE THREAD

**Issue by Misfit-Ha** [Malbryn/MalFramework#416]
**Describe the solution you'd like**
make configuring additional channels and stereo settings maybe even radio volumes easier for the mission maker.
as of now mission makers can use the the tfar module you made to set channels for LRs and SRs but they can't set additional channels and stereo settings.

**Describe alternatives you've considered**
FNF has a pretty straight forward solution you could take a look at: [fnf template](https://github.com/FridayNightFight/FNF/blob/5124621b7a24999f80d0d674d47b395d01cbdae4/FNF_MissionTemplate.VR/client/radio/fn_setRadios.sqf)

**Comment by Malbryn** [comment]
I'd say we should leave the stereo and volume settings to the player because everyone has different prefence. However, being able to set up additional channels would be a good idea.
