### ISSUE TITLE
arsenal - restricted arsenal module

### ISSUE THREAD

**Issue by Misfit-Ha** [Malbryn/MalFramework#417]
**Is your feature request related to a problem? Please describe.**
I hate having to tell players not to pick items outside their assigned role or to follow scope restrictions.

**Describe the solution you'd like**
an  (preferably ace) arsenal  that stops players from picking items, weapons and explosive outside their assigned role; and warns/stops them when they try to. for example a marksman tries to take an MAT, a message pops up saying that item is reserved for AT specialist or a regular rifleman tries to take a 12x Scope or non-engineer tries taking toolbox or satchel charges the same thing would happen with different message.

**Describe alternatives you've considered**
instead of a message poping up whenever someone picks the wrong items, the arsenal they open and items they see is created on the spot based on the array of items mission maker has assigned made to each roles. example:
`[_box, MARKSMAN_ARRAY, false] call ace_arsenal_fnc_addVirtualItems`
MARKSMAN_ARRAY being made up of a "General items array" (like bandages, magazines, vests .etc things everyone can use) plus items unique to marksman role (12x scopes, marksman rifles)

**Additional context**
this is probably a really broad request but if it helps i've seen something similar done in 77jsoc servers you can checkout.

**Comment by Malbryn** [comment]
I think the second option would be more useful because a pop-up message might not stop players from taking restricted items. :)
